- name: Configure all servers
  hosts: home
  become: true
  roles:
    - common
    - updates

- name: Configure ansible01
  hosts: ansible01.home.bischofberger.top
  become: true
  roles:
    - role: monolithprojects.github_actions_runner
      vars:
        github_account: Bischi1997
        github_repo: ansible
        access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"

- name: Configure servers with docker install
  hosts: dockerhosts
  become: true
  roles:
    - docker

- name: Configure servers with nextcloud install
  hosts: nextcloudhosts
  become: true
  roles:
    - updatenextcloud
