- name: Configure all servers
  hosts: home
  become: true
  env: 
    ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
  roles:
    - common
    - updates
# - name: Configure docker servers
#  hosts: docker01.home.bischofberger.top
#  become: true
#  roles:
#    - docker
