- name: Configure all servers
  hosts: home
  become: true
  roles:
    - common
    - updates
- name: Configure ansible01
  hosts: ansible01.home.bischofberger.top
  become: true
  roles:
    - role: monolithprojects.github_actions_runner
      vars:
          github_account: Bischi1997
          github_repo: ansible

# - name: Configure docker servers
#  hosts: docker01.home.bischofberger.top
#  become: true
#  roles:
#    - docker
