---
# update nextcloud service
- name: Execute updater.phar
  ansible.builtin.shell:
    chdir: /var/www/html/nextcloud/
    cmd: sudo -u apache php updater/updater.phar --no-interaction
- name: Update Nextcloud apps
  nextcloud.admin.run_occ:
    nextcloud_path: /var/www/nextcloud
    command: occ app:update --all
