---
- name: Install GitHub Actions Runner
  hosts: ansible01.home.bischofberger.top
  user: ansible
  become: true
  roles:
    - role: monolithprojects.github_actions_runner
        vars:
          github_account: Bischi1997
          github_repo: ansible
          access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"