---
- name: Installs zsh on Debian based systems
  ansible.builtin.apt:
    pkg:
      - zsh
  when: ansible_os_family == "Debian"

- name: Installs zsh on RedHat based systems
  ansible.builtin.dnf:
    pkg:
      - zsh
  when: ansible_os_family == "RedHat"

- name: Set ZSH as default shell for local users
  ansible.builtin.user:
    name: "{{ item }}"
    group: "{{ item }}"
    shell: /bin/zsh
  loop: "{{ local_users }}"

- name: Check if oh-my-zsh is already installed
  ansible.builtin.stat:
    path: "/home/{{ item }}/.oh-my-zsh"
  register: ohmyzsh_status
  loop: "{{ local_users }}"

- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/home/{{ item }}/install.sh"
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ local_users }}"

- name: Run oh-my-zsh installer if not already installed
  ansible.builtin.shell: |
    set -o pipefail
    yes | /home/{{ item }}/install.sh &> /dev/null
  args:
    executable: /bin/bash
    creates: "/home/{{ item }}/.oh-my-zsh"
  become: true
  become_user: "{{ item }}"
  loop: "{{ local_users }}"

- name: Remove install script
  ansible.builtin.file:
    path: "/home/{{ item }}/install.sh"
    state: absent
  loop: "{{ local_users }}"

- name: Install PowerLevel10K
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ item }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    version: master
    update: true
  loop: "{{ local_users }}"

- name: Add configuration file for PowerLevel10K to the users
  ansible.builtin.copy:
    dest: "/home/{{ item }}/.p10k.zsh"
    src: files/.p10k.zsh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0755"
  loop: "{{ local_users }}"

- name: Add Powerlevel10k config and instant prompt to .zshrc
  ansible.builtin.blockinfile:
    path: "/home/{{ item }}/.zshrc"
    create: yes
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    block: |
      # Enable Powerlevel10k instant prompt. Should be near the top of ~/.zshrc.
      if [[ -r ~/.cache/p10k-instant-prompt-${(%):-%n}.zsh ]]; then
        source ~/.cache/p10k-instant-prompt-${(%):-%n}.zsh
      fi

      # Load Powerlevel10k theme config if available
      [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Powerlevel10k"
    insertbefore: BOF
  loop: "{{ local_users }}"

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ item }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
    version: master
    update: true
  loop: "{{ local_users }}"

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ item }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1
    version: master
    update: true
  loop: "{{ local_users }}"
