---
- name: Update all Debian/Ubuntu packages to their latest version
  ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
      name: "*"
      state: latest
      force_apt_get: true
- name: Check if a reboot is needed for Debian/Ubuntu boxes
  register: reboot_required_file
  ansible.builtin.stat:
      path: /var/run/reboot-required
- name: Reboot the Debian or Ubuntu server
  ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible due to updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
  when: reboot_required_file.stat.exists
