---
- name: Install GitHub Actions Runner
  roles:
      - role: monolithprojects.github_actions_runner
        vars:
            github_account: Bischi1997
            github_repo: ansible
            access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"
