---
- name: Install GitHub Actions Runner
  hosts: ansible01.home.bischofberger.top
  user: ansible
  become: true
  vars:
    - github_account: Bischi1997
    - github_repo: ansible
  roles:
    - role: monolithprojects.github_actions_runner
