---
- name: Add local ansible user
  ansible.builtin.user:
    name: ansible
    group: ansible
    shell: /bin/bash
    home: /home/ansible
    create_home: true
    state: present
- name: Installs Standard Tools
  ansible.builtin.apt:
    pkg:
      - htop
      - nano
      - dnsutils
      - zip
      - unzip
      - fail2ban
      - rsync
      - bash-completion
- name: Add hardened SSH config
  ansible.builtin.copy:
    dest: /etc/ssh/ssh_config
    src: files/ssh_config
    owner: root
    group: root
    mode: "0600"
    validate: sshd -t -f %s
  notify: Reload sshd
