---
- name: Add local ansible user 
  user:
    name: ansible
    group: ansible
    shell: /bin/bash
    home: /home/ansible
    create_home: yes
    state: present
- name: Installs Standard Tools
  ansible.builtin.apt:
    pkg:
      - htop
      - nano
      - dnsutils
      - zip
      - unzip
      - fail2ban
      - rsync
      - bash-completion
- name: Add hardened SSH config
  copy:
    dest: /etc/ssh/ssh_config
    src: files/ssh_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH


