---
- name: Check for local ansible user and configure it
  ansible.builtin.user:
    name: ansible
    group: ansible
    shell: /bin/bash
    home: /home/ansible
    create_home: true
    state: present

- name: Installs standard tools
  ansible.builtin.apt:
    pkg:
      - bash-completion
      - htop
      - nano
      - dnsutils
      - zip
      - unzip
      - fail2ban
      - rsync
      - bash-completion
  when: ansible_os_family == "Debian"

- name: Enable EPEL Repository on CentOS machines
  ansible.builtin.dnf:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"
- name: Installs Standard Tools
  ansible.builtin.dnf:
    pkg:
      - dnf-utils
      - bash-completion
      - htop
      - nano
      - dnsutils
      - zip
      - unzip
      - fail2ban
      - rsync
      - bash-completion
  when: ansible_os_family == "RedHat"

- name: Add hardened SSH config RedHat Based
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: files/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: sshd -t -f %s
  notify: Reload sshd RedHat
  when: ansible_os_family == "RedHat"

- name: Add hardened SSH config Debian Based
  ansible.builtin.file:
    state: absent
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: files/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: sshd -t -f %s
  notify: Reload sshd Ubuntu
  when: ansible_os_family == "Debian"
