---
- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    state: latest
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable"
    state: present
- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
- name: Install Docker Module for Python
  pip:
    name: docker
