---
- name: add missing indices
  command: '{{ updatenextcloud_web_root }}/occ db:add-missing-indices'
  become: true
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false

- name: convert columns to big int
  command: '{{ updatenextcloud_web_root }}/occ db:convert-filecache-bigint --no-interaction'
  become: true
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false

- name: add mimetypes to database
  command: '{{ updatenextcloud_web_root }}/occ maintenance:mimetype:update-db'
  become: true
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false
