---
- name: Add missing indices
  ansible.builtin.command: '{{ updatenextcloud_web_root }}/occ db:add-missing-indices'
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false

- name: Convert columns to big int
  ansible.builtin.command: '{{ updatenextcloud_web_root }}/occ db:convert-filecache-bigint --no-interaction'
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false

- name: Add mimetypes to database
  ansible.builtin.command: '{{ updatenextcloud_web_root }}/occ maintenance:mimetype:update-db'
  become_user: "{{ updatenextcloud_service_user }}"
  changed_when: false
