# code: language=yaml
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'
    schedule:
        - cron: "0 4 * * 1"

jobs:
    execute_ansible_playbooks:
        runs-on: "self-hosted"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # needed for progressive mode to work
            - name: Run production playbooks
              uses: arillso/action.playbook@master
              with:
                  playbook: sites.yml
                  inventory: inventory/production.yml
                  private_key: ${{secrets.ANSIBLE_SSH_KEY}}
                  vault_password: ${{ secrets.VAULT_PASSWORD }}
                  galaxy_file: requirements.yml
        env:
            ANSIBLE_HOST_KEY_CHECKING: False
            PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            ROOT_USER_PUBKEY: ${{ secrets.ROOT_USER_PUBKEY }}
            ANSIBLE_USER_PUBKEY: ${{ secrets.ANSIBLE_USER_PUBKEY }}
            BISCHI_USER_PUBKEY: ${{ secrets.BISCHI_USER_PUBKEY }}
