# code: language=yaml
on: [workflow_dispatch, push]
jobs:
    run_hetzner_playbook:
        runs-on: "self-hosted"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # needed for progressive mode to work
            - name: Lint Ansible Playbook
              uses: ansible/ansible-lint@main
            - name: Run production playbooks
              uses: arillso/action.playbook@master
              with:
                  playbook: sites.yml
                  inventory: inventory/production.yml
                  private_key: ${{secrets.ANSIBLE_SSH_KEY}}
        env:
            ANSIBLE_HOST_KEY_CHECKING: False
