# code: language=yaml
on: [workflow_dispatch]
jobs:
    run_hetzner_playbook:
      runs-on: "ubuntu-latest"
      steps:
      - uses: actions/checkout@v3
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: ""
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: roles/common/tasks/main.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, SSH private key
          key: ${{secrets.ANSIBLE_SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [hetzner]